---
# Create directories if they are missing
- name: create all required directories
  file: path={{ item }} state=directory
  with_items:
   - "{{ deploy_home }}/bin"
   - "{{ deploy_home }}/bin/pid"

# bin control files

- name: installing control script
  template: src="../files/raven.sh.j2" dest="{{ deploy_home }}/bin/raven.sh" mode=755 backup=yes
